config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :categories do
      resources :exchanges
    end
  end
 
  root "users#index"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_and_belongs_to_many :exchanges, join_table: :categories_exchanges
  validates :name, presence: true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :categories, join_table: :categories_exchanges
  validates :name, presence: true
  validates :categories, presence: { message: 'must select at least one category' }
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  has_many :exchanges, foreign_key: 'author_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    user_categories_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user_id: current_user.id)
    @exchanges_by_category = {}

    @categories.each do |category|
      @exchanges_by_category[category.id] = category.exchanges
    end
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @user = current_user
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      # Category successfully created
      flash[:notice] = 'Category created successfully.'
      redirect_to user_categories_path(current_user)
    else
      # Handle validation errors
      flash[:notice] = 'Category not created successfully.'
      render :new
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :authenticate_user!

  # GET /exchanges or /exchanges.json
  def index
    # @exchanges = Exchange.all
    @category = current_user.categories.find(params[:category_id])
    @exchanges = @category.exchanges.order(created_at: :desc)
  end

  # GET /exchanges/1 or /exchanges/1.json
  def show; end

  # GET /exchanges/new
  def new
    @category = current_user.categories.find(params[:category_id])
    @categories = Category.where(user_id: current_user.id)
    @exchange = Exchange.new
  end

  # GET /exchanges/1/edit
  def edit; end

  # POST /exchanges or /exchanges.json
  def create
    @exchange = current_user.exchanges.build(exchange_params)
    @category = current_user.categories.find(params[:category_id])

    if @exchange.save
      # Category successfully created
      flash[:notice] = 'Transaction created successfully.'
      redirect_to user_category_exchanges_path(current_user, @category)
    else
      # Handle validation errors
      flash[:notice] = 'Transaction not created successfully.'
      render :new
    end
  end

  # PATCH/PUT /exchanges/1 or /exchanges/1.json
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to exchange_url(@exchange), notice: 'Exchange was successfully updated.' }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1 or /exchanges/1.json
  def destroy
    @exchange.destroy

    respond_to do |format|
      format.html { redirect_to exchanges_url, notice: 'Exchange was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exchange
    @exchange = Exchange.find(params[:id])
  end

  # Only allow a list of trusted parameters through.

  def exchange_params
    params.require(:exchange).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class="categories" id="<%= dom_id category %>">
<% total_amount = category.exchanges.sum(&:amount) %>
 <div class="category">
 <div class="details">
 <img src="<%= category.icon %>" alt="icon" class="icon"/>
 <div class="c-name"><a href = "<%= user_category_exchanges_path(current_user,category) %>"><%= category.name %></a></div>
 </div>
 <div class="transaction">Total amount: <%= total_amount %></div>
 </div>
</div>

app/views/categories/_form.html.erb
<div class="c-container">
<%= form_with(model: category, url: user_categories_path(current_user)) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-container">
  <div class="header">
   <%= link_to "Back", user_categories_path(current_user), class: "btn" %>
  <h3 class="title">Add new Category</h3>
  <div>
     <%= form.submit "Add Category", class: "btn" %>
  </div>
   </div>

  <div class="field">
  <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "input", placeholder: "Name" %>
  </div>

  <div class="field">
  <%= form.text_field :icon, autofocus: true, autocomplete: "name", class: "input", placeholder: "URL" %>
  </div>

 
<% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="c-c">
<div class="c-container">
 <div class="header">
  <%= link_to "New", new_user_category_path, class: "btn" %>
  <h3 class="title">CATEGORY</h3>
  <div class="sign-out">
  <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "btn" %>
  </div>
  </div>

<div id="categories">
 
  <% if @categories.empty? %>
      <p>No categories found.</p>
    <% else %>
      <% @categories.each do |category| %>
        <%= render category %>
      <% end %>
    <% end %>
</div>
</div>
<div class="new">
<%= link_to "New category", new_user_category_path, class: "new-data" %>
</div>
</div>
<p style="color: green"><%= notice %></p>

app/views/categories/new.html.erb
 

<%= render "form", category: @category %>

<br>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/exchanges/_exchange.html.erb
<div class="categories" id="<%= dom_id exchange %>">
 
 <div class="category">
 <div class="details">
 <div class="c-name"><h4><%= exchange.name %></h4></div>
 </div>
 <div class="transaction">Amount: $<%= exchange.amount %></div>
 </div>

</div>

 

app/views/exchanges/_form.html.erb
<div class="c-container">
<%= form_with(model: exchange, url: user_category_exchanges_path(current_user, @category)) do |form| %>
  <% if exchange.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
        <% exchange.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-container">
  <div class="header">
    <%= link_to "Back", user_category_exchanges_path(current_user, @category), class: "btn" %>
  <h3 class="title">Add new Transaction</h3>
  <div>
     <%= form.submit "Add Transaction", class: "btn" %>
  </div>
  </div>

  <div class="field">
  <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "input", placeholder: "Name" %>
  </div>

  <div class="field">
  <%= form.text_field :amount, autofocus: true, autocomplete: "Amount", class: "input", placeholder: "Amount" %>
  </div>

  <div class="field">
  <%= form.collection_select :category_ids, @categories, :id, :name, { include_blank: "Select a category" }, { class: "input", multiple: true } %>
  </div>
   
<% end %>
</div>

app/views/exchanges/edit.html.erb
<h1>Editing exchange</h1>

<%= render "form", exchange: @exchange %>

<br>

<div>
  <%= link_to "Show this exchange", @exchange %> |
  <%= link_to "Back to exchanges", exchanges_path %>
</div>

app/views/exchanges/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="c-c">
<div class="c-container">
 <div class="header">
  <%= link_to "Back", user_categories_path(current_user), class: "btn" %>
  <h3 class="title">TRANSACTION</h3>
  <div class="sign-out">
  <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "btn" %>
  </div>
  </div>
 
<div id="exchanges">
<% total_amount = @exchanges.sum(&:amount) %>
<div  class="total-amount"><h3>Total amount: $<%= total_amount %></h3></div>
  <% @exchanges.each do |exchange| %>
    <%= render exchange %>
     
  <% end %>
</div>
</div>
<div class="new">
<%= link_to "New Transaction", new_user_category_exchange_path(current_user, @category), class: "new-data" %>
</div>
</div>

app/views/exchanges/new.html.erb
 <p style="color: red"><%= notice %></p>

<%= render "form", exchange: @exchange %>

<br>

 

app/views/exchanges/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exchange %>

<div>
  <%= link_to "Edit this exchange", edit_exchange_path(@exchange) %> |
  <%= link_to "Back to exchanges", exchanges_path %>

  <%= button_to "Destroy this exchange", @exchange, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

 <div class="splash-container">
 <div class="logo-container">
 <h3>MyBudget</h3>
 </div>
 <div class="link-container">
 <div class="link active">
   <%= link_to "Log in",  new_user_session_path, class: "a"%>
 </div>
 <div class="link">
   <%= link_to "Sign up", new_user_registration_path, class: "a" %> 
 </div>
 </div>
 
 
 </div>

 
 

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>